In [1]:
import numpy as np

In [2]:
data = np.array([
    [0.2, 0.1],
    [0.4, 0.2],
    [-0.7, -0.6],
    [-0.2, 0.5],
    [0.5, -0.7]
])

In [3]:
label = np.array([
    [2,3,5],
    [6,5,1],
    [-5,7,3],
    [-1,3,9],
    [1,2,3]
])

In [ ]:
class Dense:
    def __init__():
        self.w = np.random()
        self.b = np.random()


In [9]:
label_0 = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
])

label_1 = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 1, 1, 0],
])

label_2 = np.array([
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
])

label_3 = np.array([
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
])

label_4 = np.array([
    [1, 0, 0, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1],
])

label_5 = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
])

In [14]:
input_pattern_0 = label_0.flatten() #(5x5 -> 25x1)

y_0=0

In [ ]:
print(input_pattern_0.shape)

In [15]:
# one hot code / 타겟 = 1, 나머지 = 0
label_one_hot=np.zeros(10)
label_one_hot[y_0]=1

In [ ]:
# input size = 25x1 (flatten)
# output size = 10x1
input_size=25
output_size=10

w=np.random.random(input_size)
b=np.random.random()

# w 전치행렬로 만든 후 행렬 곱 연산
def perceptron(x, w, b):
    weighted_sum = np.dot(x, w) + b
    activation = 1 / (1 + np.exp(-weighted_sum))
    return activation

In [ ]:
output = perceptron(input_pattern_0, w,b)
print(f"Output, {output}")

# 단층 퍼셉트론

In [1]:
import numpy as np

# Define the labels (5x5 arrays)
labels = np.array([
    [
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0],
    ],
    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
    ],
    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
    ],
    [
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
    ],
    [
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
    ]
])

# Corresponding labels (0-5)
targets = np.array([1, 2, 3, 4, 5])

# Prepare the input and output data
X = np.array([label.flatten() for label in labels])  # Flatten each label (5x5 -> 25x1)
y = np.zeros((len(targets), 5))  # One-hot encode the targets
for i, target in enumerate(targets):
    y[i, target-1] = 1

print("Input shape (X):", X.shape)  # Should be (5, 25)
print("Output shape (y):", y.shape)  # Should be (5, 5)

# Example perceptron model
input_size = X.shape[1]  # 25
output_size = y.shape[1]  # 5

# (5,25) x (25,5) = (5,5)
# Initialize weights and bias
w = np.random.random((input_size, output_size))  # Shape: (5, 25)
b = np.random.random(output_size)  # Shape: (5,)

def perceptron(x, w, b):
    """
    Perceptron function for multi-class classification.
    """
    weighted_sum = x @ w + b  # Shape: (5,)
    return weighted_sum

def softmax(a): # (b, n)
    y = np.exp(a) / np.sum(np.exp(a), axis=1, keepdims=True)
    return y

output = softmax(perceptron(X,w,b))
print("Output for sample 0:", output)

Input shape (X): (5, 25)
Output shape (y): (5, 5)
Output for sample 0: [[0.14498756 0.112302   0.24668721 0.33645497 0.15956827]
 [0.04076317 0.06350774 0.53724803 0.29726253 0.06121853]
 [0.03828966 0.14115689 0.45083258 0.26931452 0.10040635]
 [0.02832849 0.39673906 0.43786409 0.06771374 0.06935462]
 [0.05546969 0.09530139 0.47318398 0.28528454 0.09076041]]


In [ ]:
print(X, w, b, y)

In [ ]:
# y = output
# t = target
def mse_loss(y, t):
    return np.mean((y - t) ** 2)

def mse_loss_gradient(y, t):
    return (2 / y.shape[0]) * (y - t)

In [ ]:
print(mse_loss(softmax(perceptron(X,w,b)),y))

In [3]:
import numpy as np

In [4]:
class Dense:
    def __init__(self, input_size, output_size, learning_rate=0.01):
        self.input_size = input_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        self.weights = np.random.randn(input_size, output_size) * 0.01 # 가우시안 정규 분포로 랜덤하게 초기화 (초기화 방법 수정해야함)
        self.bias = np.zeros(output_size)

    def forward(self, X):
        self.input = X
        return X @ self.weights + self.bias


    def backward(self, loss_grad):
        grad_weights = self.input.T @ loss_grad
        grad_bais = np.sum(loss_grad, axis=0)

        grad_input = loss_grad @ self.weights.T

        self.weights -= self.learning_rate * grad_weights
        self.bias -= self.learning_rate * grad_bais

        return grad_input

class Softmax:
    def forward(self, X):
        y = np.exp(X) / np.sum(np.exp(X), axis=1, keepdims=True)
        return y
    
    def backward(self, dx_out):
        return dx_out

class CategoricalCrossEntropy:
    def forward(self, y_pred, y_true):
        self.y_pred = y_pred
        self.y_true = y_true
        
        return -np.sum(y_true*np.log(y_pred))
    
    def backward(self):
        return self.y_pred - self.y_true

    
class Mse_loss:
    def forward(self, y_pred, y_true):
        self.y_pred = y_pred
        self.y_true = y_true
        return np.mean((y_pred-y_true)**2)
    
    def backward(self):
        batch_size = self.y_pred.shape[0]
        return (2 / batch_size) * (self.y_pred-self.y_true)

class Sequential:
    def __init__(self, layers) -> None:
        self.layers = layers

    def forward(self, x: np.ndarray):
        outputs = []
        for layer in self.layers:
            x = layer.forward(x)
            outputs.append(x)
        return outputs[-1] # forward 진행 시 outputs 리스트에 append하게 되는데 마지막 레이어의 output 값을 return 하기 위해 outputs[-1]을 return 한다다

    def backward(self, loss_grad: np.ndarray):
        grad = loss_grad
        for layer in reversed(self.layers): # 레이어의 역순으로 grad값을 업데이트한다다
            grad = layer.backward(grad)
        return grad

In [5]:
layers = Sequential([
    Dense(25, 5),
    Softmax()
])
loss=CategoricalCrossEntropy()

In [6]:
import numpy as np

# Define the labels (5x5 arrays)
labels = np.array([
    [
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0],
    ],
    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
    ],
    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
    ],
    [
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
    ],
    [
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
    ]
])

# Corresponding labels (0-5)
targets = np.array([1, 2, 3, 4, 5])

X = np.array([label.flatten() for label in labels])  # Flatten each label (5x5 -> 25x1)
y = np.zeros((len(targets), 5))  # One-hot encode the targets
for i, target in enumerate(targets):
    y[i, target-1] = 1

epochs = 1000
for epoch in range(epochs):
    y_pred=layers.forward(X)

    loss_value = loss.forward(y_pred, y)

    grad_out=loss.backward()
    layers.backward(grad_out)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss : {loss_value}")

Epoch 0, Loss : 8.013184966086884
Epoch 10, Loss : 6.58757986910486
Epoch 20, Loss : 5.581384932541907
Epoch 30, Loss : 4.806026232710713
Epoch 40, Loss : 4.204102815168264
Epoch 50, Loss : 3.731139726283908
Epoch 60, Loss : 3.352615936148978
Epoch 70, Loss : 3.043581637651612
Epoch 80, Loss : 2.7865253523907465
Epoch 90, Loss : 2.569162156648956
Epoch 100, Loss : 2.3827553167290314
Epoch 110, Loss : 2.2209697569367437
Epoch 120, Loss : 2.0791147253891884
Epoch 130, Loss : 1.953645296756675
Epoch 140, Loss : 1.8418309442690939
Epoch 150, Loss : 1.7415316270797163
Epoch 160, Loss : 1.651043706429586
Epoch 170, Loss : 1.5689918886200849
Epoch 180, Loss : 1.4942520298712823
Epoch 190, Loss : 1.4258950068674774
Epoch 200, Loss : 1.363145222598574
Epoch 210, Loss : 1.3053494549496696
Epoch 220, Loss : 1.2519531340692656
Epoch 230, Loss : 1.2024820377658674
Epoch 240, Loss : 1.1565279954835508
Epoch 250, Loss : 1.1137375980258895
Epoch 260, Loss : 1.0738031893551407
Epoch 270, Loss : 1.03645

In [7]:
layers.forward(X)


array([[0.98344941, 0.00505547, 0.0044613 , 0.00202382, 0.00501   ],
       [0.001903  , 0.93920295, 0.04803932, 0.00209331, 0.00876141],
       [0.00293025, 0.0472595 , 0.89421591, 0.00805075, 0.0475436 ],
       [0.00108336, 0.00217839, 0.01526053, 0.97929427, 0.00218346],
       [0.00188237, 0.00882746, 0.04825068, 0.0020353 , 0.93900419]])

In [12]:
test_input = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 1],
])

test_input_flattened = test_input.flatten().reshape(1,-1)

predicted_output = layers.forward(test_input_flattened)

predicted_class = np.argmax(predicted_output, axis=1) + 1

print(f"Predicted Class : {predicted_class[0]}")

Predicted Class : 2


In [52]:
print(predicted_class)

[1]


In [55]:
def calculate_accuracy(y_true, y_pred):
    correct_predictions = np.sum(y_true == y_pred)
    total_predictions = len(y_true)
    return correct_predictions / total_predictions

# 예측 수행
y_pred_classes = np.argmax(layers.forward(X), axis=1) + 1  # 1-based 클래스 예측
accuracy = calculate_accuracy(targets, y_pred_classes)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%
